name: 'Setup SetOps'
description: 'Sets up the SetOps CLI in your GitHub Actions workflow.'
author: 'SetOps'
inputs:
  setops_version:
    description: 'The version of SetOps CLI to install. Instead of a full version string you can also specify a constraint string. Examples are: `<0.1.5`, `~0.1.4`, `0.1.x` (all three installing the latest available 0.1.4 version). Defaults to `latest`.'
    default: 'latest'
    required: false
  setops_client:
    description: 'The SetOps client name to login to. The client name is the part before .setops.net. If not set, no login will be executed.'
    required: false
  setops_username:
    description: 'The SetOps username for a SetOps service to login in. If not set, no login will be executed.'
    required: false
  setops_password:
    description: 'The SetOps password for a SetOps service to login in. If not set, no login will be executed.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'white'
