name: 'action-test'

on:
  push:
    branches: [main]
  pull_request:

jobs:
  setops-versions:
    name: 'SetOps Versions'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        setops_versions: ["0.6.1", latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SetOps - ${{ matrix['setops_versions'] }}
      uses: ./
      with:
        setops_version: ${{ matrix['setops_versions'] }}
        setops_client: dev
        setops_username: setup-setops-action-ci@zweitag.de
        setops_password: ${{ secrets.SETOPS_PASSWORD }}

    - name: Validate SetOps Version - ${{ matrix['setops_versions'] }}
      if: ${{ matrix['setops_versions'] != 'latest' }}
      run: |
        setops version
        setops version | grep "CLI Version:      ${{ matrix['setops_versions']}}"

    - name: Validate SetOps Version - ${{ matrix['setops_versions'] }}
      if: ${{ matrix['setops_versions'] == 'latest' }}
      run: |
        setops version
        setops version | grep "CLI Version:      "

    - name: setops logout
      run: setops logout

  setops-versions-constraints:
    name: 'SetOps Versions Constraints'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        setops_versions: [~0.1, 0.1.x, <0.2.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SetOps - ${{ matrix['setops_versions'] }}
      uses: ./
      with:
        setops_version: ${{ matrix['setops_versions'] }}

    - name: Validate SetOps Version - ${{ matrix['setops_versions'] }}
      run: |
        setops version show | grep "CLI Version:      0\.1"

  setops-with-login:
    name: 'SetOps Credentials'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SetOps
      uses: ./
      with:
        setops_client: dev
        setops_username: setup-setops-action-ci@zweitag.de
        setops_password: ${{ secrets.SETOPS_PASSWORD }}

    - name: Validate successful login
      run: setops project | grep "NAME"

    - name: setops logout
      run: setops logout
