name: 'action-test'

on:
  push:
    branches: [main]
  pull_request:

jobs:
  setops-versions:
    name: 'SetOps Versions'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        setops_versions: ["0.9.0", latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SetOps - ${{ matrix['setops_versions'] }}
      uses: ./
      with:
        setops_version: ${{ matrix['setops_versions'] }}
        setops_organization: dev
        setops_username: setup-setops-action-ci@zweitag.de
        setops_password: ${{ secrets.SETOPS_PASSWORD }}
        setops_api_url: ${{ secrets.SETOPS_API_URL }}

    - name: Validate SetOps Version - ${{ matrix['setops_versions'] }}
      if: ${{ matrix['setops_versions'] != 'latest' }}
      run: |
        setops version
        setops version | grep "CLI Version:      ${{ matrix['setops_versions']}}"

    - name: Validate SetOps Version - ${{ matrix['setops_versions'] }}
      if: ${{ matrix['setops_versions'] == 'latest' }}
      run: |
        setops version
        setops version | grep "CLI Version:      "

    - name: setops logout
      run: setops logout

  setops-versions-constraints:
    name: 'SetOps Versions Constraints'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        setops_versions: [~0.8, 0.8.x, <0.9.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SetOps - ${{ matrix['setops_versions'] }}
      uses: ./
      with:
        setops_version: ${{ matrix['setops_versions'] }}

    - name: Validate SetOps Version - ${{ matrix['setops_versions'] }}
      run: |
        setops version | grep "CLI Version:      0\.8"

  setops-with-login:
    name: 'SetOps Credentials'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SetOps
      uses: ./
      with:
        setops_api_url: ${{ secrets.SETOPS_API_URL }}
        setops_organization: dev
        setops_password: ${{ secrets.SETOPS_PASSWORD }}
        setops_username: setup-setops-action-ci@zweitag.de

    - name: Validate successful login
      run: setops project | grep "NAME"

    - name: setops logout
      run: setops logout
