name: 'build-test'

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install
      run: npm clean-install

    - name: Verify
      run: |
        npm run build
        # Fail if "npm run build" generated new changes in dist
        git update-index --refresh dist/* && git diff-index --quiet HEAD dist

    - name: Test
      run: npm test
